// verses.js - Base de datos ampliada (Reina Valera 1960)
const versesDB = [
    // --- SALMOS Y PROVERBIOS ---
    { r: "Salmos 23:1", t: "Jehová es mi pastor; nada me faltará." },
    { r: "Salmos 23:4", t: "Aunque ande en valle de sombra de muerte, no temeré mal alguno, porque tú estarás conmigo." },
    { r: "Salmos 91:1", t: "El que habita al abrigo del Altísimo morará bajo la sombra del Omnipotente." },
    { r: "Salmos 91:2", t: "Diré yo a Jehová: Esperanza mía, y castillo mío; mi Dios, en quien confiaré." },
    { r: "Salmos 91:11", t: "Pues a sus ángeles mandará acerca de ti, que te guarden en todos tus caminos." },
    { r: "Salmos 121:1-2", t: "Alzaré mis ojos a los montes; ¿De dónde vendrá mi socorro? Mi socorro viene de Jehová, que hizo los cielos y la tierra." },
    { r: "Salmos 27:1", t: "Jehová es mi luz y mi salvación; ¿de quién temeré? Jehová es la fortaleza de mi vida; ¿de quién he de atemorizarme?" },
    { r: "Salmos 37:4", t: "Deléitate asimismo en Jehová, y él te concederá las peticiones de tu corazón." },
    { r: "Salmos 46:1", t: "Dios es nuestro amparo y fortaleza, nuestro pronto auxilio en las tribulaciones." },
    { r: "Salmos 119:105", t: "Lámpara es a mis pies tu palabra, y lumbrera a mi camino." },
    { r: "Salmos 103:1", t: "Bendice, alma mía, a Jehová, y bendiga todo mi ser su santo nombre." },
    { r: "Salmos 19:1", t: "Los cielos cuentan la gloria de Dios, y el firmamento anuncia la obra de sus manos." },
    { r: "Salmos 34:8", t: "Gustad, y ved que es bueno Jehová; dichoso el hombre que confía en él." },
    { r: "Salmos 51:10", t: "Crea en mí, oh Dios, un corazón limpio, y renueva un espíritu recto dentro de mí." },
    { r: "Salmos 1:1", t: "Bienaventurado el varón que no anduvo en consejo de malos, ni estuvo en camino de pecadores." },
    { r: "Salmos 139:14", t: "Te alabaré; porque formidables, maravillosas son tus obras." },
    { r: "Salmos 150:6", t: "Todo lo que respira alabe a JAH. Aleluya." },
    { r: "Salmos 118:24", t: "Este es el día que hizo Jehová; nos gozaremos y alegraremos en él." },
    { r: "Salmos 100:4", t: "Entrad por sus puertas con acción de gracias, por sus atrios con alabanza." },
    { r: "Salmos 42:1", t: "Como el ciervo brama por las corrientes de las aguas, así clama por ti, oh Dios, el alma mía." },
    { r: "Salmos 56:3", t: "En el día que temo, yo en ti confío." },
    { r: "Proverbios 3:5", t: "Fíate de Jehová de todo tu corazón, y no te apoyes en tu propia prudencia." },
    { r: "Proverbios 3:6", t: "Reconócelo en todos tus caminos, y él enderezará tus veredas." },
    { r: "Proverbios 4:23", t: "Sobre toda cosa guardada, guarda tu corazón; porque de él mana la vida." },
    { r: "Proverbios 16:3", t: "Encomienda a Jehová tus obras, y tus pensamientos serán afirmados." },
    { r: "Proverbios 18:10", t: "Torre fuerte es el nombre de Jehová; a él correrá el justo, y será levantado." },
    { r: "Proverbios 17:17", t: "En todo tiempo ama el amigo, y es como un hermano en tiempo de angustia." },
    { r: "Proverbios 22:6", t: "Instruye al niño en su camino, y aun cuando fuere viejo no se apartará de él." },
    { r: "Proverbios 1:7", t: "El principio de la sabiduría es el temor de Jehová." },
    { r: "Proverbios 15:1", t: "La blanda respuesta quita la ira; mas la palabra áspera hace subir el furor." },

    // --- EVANGELIOS Y HECHOS ---
    { r: "Juan 3:16", t: "Porque de tal manera amó Dios al mundo, que ha dado a su Hijo unigénito, para que todo aquel que en él cree, no se pierda, mas tenga vida eterna." },
    { r: "Juan 14:6", t: "Jesús le dijo: Yo soy el camino, y la verdad, y la vida; nadie viene al Padre, sino por mí." },
    { r: "Juan 11:25", t: "Le dijo Jesús: Yo soy la resurrección y la vida; el que cree en mí, aunque esté muerto, vivirá." },
    { r: "Juan 10:10", t: "El ladrón no viene sino para hurtar y matar y destruir; yo he venido para que tengan vida, y para que la tengan en abundancia." },
    { r: "Juan 1:1", t: "En el principio era el Verbo, y el Verbo era con Dios, y el Verbo era Dios." },
    { r: "Juan 8:32", t: "Y conoceréis la verdad, y la verdad os hará libres." },
    { r: "Juan 16:33", t: "Estas cosas os he hablado para que en mí tengáis paz. En el mundo tendréis aflicción; pero confiad, yo he vencido al mundo." },
    { r: "Mateo 11:28", t: "Venid a mí todos los que estáis trabajados y cargados, y yo os haré descansar." },
    { r: "Mateo 28:20", t: "Y he aquí yo estoy con vosotros todos los días, hasta el fin del mundo. Amén." },
    { r: "Mateo 6:33", t: "Mas buscad primeramente el reino de Dios y su justicia, y todas estas cosas os serán añadidas." },
    { r: "Mateo 5:14", t: "Vosotros sois la luz del mundo; una ciudad asentada sobre un monte no se puede esconder." },
    { r: "Mateo 7:7", t: "Pedid, y se os dará; buscad, y hallaréis; llamad, y se os abrirá." },
    { r: "Marcos 9:23", t: "Jesús le dijo: Si puedes creer, al que cree todo le es posible." },
    { r: "Lucas 1:37", t: "Porque nada hay imposible para Dios." },
    { r: "Hechos 1:8", t: "Pero recibiréis poder, cuando haya venido sobre vosotros el Espíritu Santo." },
    { r: "Hechos 4:12", t: "Y en ningún otro hay salvación; porque no hay otro nombre bajo el cielo, dado a los hombres, en que podamos ser salvos." },
    { r: "Hechos 16:31", t: "Cree en el Señor Jesucristo, y serás salvo, tú y tu casa." },

    // --- CARTAS DE PABLO ---
    { r: "Romanos 8:28", t: "Y sabemos que a los que aman a Dios, todas las cosas les ayudan a bien." },
    { r: "Romanos 8:31", t: "¿Qué, pues, diremos a esto? Si Dios es por nosotros, ¿quién contra nosotros?" },
    { r: "Romanos 8:38-39", t: "Por lo cual estoy seguro de que ni la muerte, ni la vida... nos podrá separar del amor de Dios." },
    { r: "Romanos 12:2", t: "No os conforméis a este siglo, sino transformaos por medio de la renovación de vuestro entendimiento." },
    { r: "Romanos 10:9", t: "Que si confesares con tu boca que Jesús es el Señor... serás salvo." },
    { r: "Romanos 5:8", t: "Mas Dios muestra su amor para con nosotros, en que siendo aún pecadores, Cristo murió por nosotros." },
    { r: "Filipenses 4:13", t: "Todo lo puedo en Cristo que me fortalece." },
    { r: "Filipenses 4:6", t: "Por nada estéis afanosos, sino sean conocidas vuestras peticiones delante de Dios." },
    { r: "Filipenses 4:7", t: "Y la paz de Dios, que sobrepasa todo entendimiento, guardará vuestros corazones." },
    { r: "Filipenses 1:6", t: "Estando persuadido de esto, que el que comenzó en vosotros la buena obra, la perfeccionará hasta el día de Jesucristo." },
    { r: "2 Corintios 5:7", t: "Porque por fe andamos, no por vista." },
    { r: "2 Corintios 5:17", t: "De modo que si alguno está en Cristo, nueva criatura es; las cosas viejas pasaron; he aquí todas son hechas nuevas." },
    { r: "2 Corintios 12:9", t: "Y me ha dicho: Bástate mi gracia; porque mi poder se perfecciona en la debilidad." },
    { r: "Gálatas 2:20", t: "Con Cristo estoy juntamente crucificado, y ya no vivo yo, mas vive Cristo en mí." },
    { r: "Gálatas 5:22", t: "Mas el fruto del Espíritu es amor, gozo, paz, paciencia, benignidad, bondad, fe, mansedumbre, templanza." },
    { r: "Efesios 2:8", t: "Porque por gracia sois salvos por medio de la fe; y esto no de vosotros, pues es don de Dios." },
    { r: "Efesios 6:11", t: "Vestíos de toda la armadura de Dios, para que podáis estar firmes contra las asechanzas del diablo." },
    { r: "Efesios 3:20", t: "Y a Aquel que es poderoso para hacer todas las cosas mucho más abundantemente de lo que pedimos o entendemos." },
    { r: "Colosenses 3:23", t: "Y todo lo que hagáis, hacedlo de corazón, como para el Señor y no para los hombres." },
    { r: "1 Tesalonicenses 5:17", t: "Orad sin cesar." },
    { r: "1 Tesalonicenses 5:18", t: "Dad gracias en todo, porque esta es la voluntad de Dios para con vosotros." },
    { r: "2 Timoteo 1:7", t: "Porque no nos ha dado Dios espíritu de cobardía, sino de poder, de amor y de dominio propio." },
    { r: "Hebreos 11:1", t: "Es, pues, la fe la certeza de lo que se espera, la convicción de lo que no se ve." },
    { r: "Hebreos 13:8", t: "Jesucristo es el mismo ayer, y hoy, y por los siglos." },
    { r: "Hebreos 4:12", t: "Porque la palabra de Dios es viva y eficaz, y más cortante que toda espada de dos filos." },

    // --- OTROS LIBROS ---
    { r: "Isaías 40:31", t: "Pero los que esperan a Jehová tendrán nuevas fuerzas; levantarán alas como las águilas." },
    { r: "Isaías 41:10", t: "No temas, porque yo estoy contigo; no desmayes, porque yo soy tu Dios que te esfuerzo." },
    { r: "Isaías 53:5", t: "Mas él herido fue por nuestras rebeliones, molido por nuestros pecados." },
    { r: "Isaías 54:17", t: "Ninguna arma forjada contra ti prosperará." },
    { r: "Isaías 9:6", t: "Porque un niño nos es nacido, hijo nos es dado... y se llamará su nombre Admirable, Consejero, Dios Fuerte." },
    { r: "Jeremías 29:11", t: "Porque yo sé los pensamientos que tengo acerca de vosotros, dice Jehová, pensamientos de paz." },
    { r: "Jeremías 33:3", t: "Clama a mí, y yo te responderé, y te enseñaré cosas grandes y ocultas que tú no conoces." },
    { r: "Josué 1:9", t: "Mira que te mando que te esfuerces y seas valiente; no temas ni desmayes." },
    { r: "Josué 24:15", t: "Pero yo y mi casa serviremos a Jehová." },
    { r: "Lamentaciones 3:22-23", t: "Por la misericordia de Jehová no hemos sido consumidos, porque nunca decayeron sus misericordias." },
    { r: "Miqueas 6:8", t: "Oh hombre, él te ha declarado lo que es bueno... hacer justicia, y amar misericordia." },
    { r: "Sofonías 3:17", t: "Jehová está en medio de ti, poderoso, él salvará." },
    { r: "Habacuc 3:19", t: "Jehová el Señor es mi fortaleza." },
    { r: "Santiago 1:5", t: "Y si alguno de vosotros tiene falta de sabiduría, pídala a Dios." },
    { r: "Santiago 4:7", t: "Someteos, pues, a Dios; resistid al diablo, y huirá de vosotros." },
    { r: "1 Pedro 5:7", t: "Echando toda vuestra ansiedad sobre él, porque él tiene cuidado de vosotros." },
    { r: "1 Juan 1:9", t: "Si confesamos nuestros pecados, él es fiel y justo para perdonar nuestros pecados." },
    { r: "1 Juan 4:19", t: "Nosotros le amamos a él, porque él nos amó primero." },
    { r: "Apocalipsis 3:20", t: "He aquí, yo estoy a la puerta y llamo." },
    { r: "Apocalipsis 21:4", t: "Enjugará Dios toda lágrima de los ojos de ellos; y ya no habrá muerte." }
];
