export const versesDB = [
  // --- FELICIDAD (HAPPY) ---
  { t: "Este es el día que hizo Jehová; nos gozaremos y alegraremos en él.", r: "Salmos 118:24", m: ["happy"] },
  { t: "El corazón alegre hermosea el rostro.", r: "Proverbios 15:13", m: ["happy"] },
  { t: "Gozaos en el Señor siempre; otra vez digo: ¡Gozaos!", r: "Filipenses 4:4", m: ["happy"] },
  { t: "El gozo de Jehová es vuestra fuerza.", r: "Nehemías 8:10", m: ["happy"] },
  { t: "Me mostrarás la senda de la vida; en tu presencia hay plenitud de gozo.", r: "Salmos 16:11", m: ["happy"] },
  { t: "El corazón alegre constituye buen remedio.", r: "Proverbios 17:22", m: ["happy"] },
  { t: "Grandes cosas ha hecho Jehová con nosotros; estaremos alegres.", r: "Salmos 126:3", m: ["happy"] },
  { t: "Cantad alegres a Dios, habitantes de toda la tierra.", r: "Salmos 100:1", m: ["happy"] },
  { t: "Has cambiado mi lamento en baile; desataste mi cilicio, y me ceñiste de alegría.", r: "Salmos 30:11", m: ["happy"] },
  { t: "En gran manera me gozaré en Jehová, mi alma se alegrará en mi Dios.", r: "Isaías 61:10", m: ["happy"] },
  { t: "Jehová es mi fortaleza y mi escudo; en él confió mi corazón, y fui ayudado, por lo que se gozó mi corazón.", r: "Salmos 28:7", m: ["happy"] },
  { t: "Estad siempre gozosos.", r: "1 Tesalonicenses 5:16", m: ["happy"] },
  { t: "Y el Dios de esperanza os llene de todo gozo y paz en el creer.", r: "Romanos 15:13", m: ["happy"] },
  { t: "Tú diste alegría a mi corazón mayor que la de ellos cuando abundaba su grano y su mosto.", r: "Salmos 4:7", m: ["happy"] },
  { t: "Mas los justos se alegrarán; se gozarán delante de Dios, y saltarán de alegría.", r: "Salmos 68:3", m: ["happy"] },
  { t: "Por cuanto tú, oh Jehová, me has alegrado con tus obras; en las obras de tus manos me gozo.", r: "Salmos 92:4", m: ["happy"] },
  { t: "No tengo yo mayor gozo que este, el oír que mis hijos andan en la verdad.", r: "3 Juan 1:4", m: ["happy"] },
  { t: "Aunque la higuera no florezca... Con todo, yo me alegraré en Jehová.", r: "Habacuc 3:17-18", m: ["happy"] },
  { t: "Jehová tu Dios está en medio de ti... se gozará sobre ti con alegría.", r: "Sofonías 3:17", m: ["happy"] },
  { t: "Sacaréis con gozo aguas de las fuentes de la salvación.", r: "Isaías 12:3", m: ["happy"] },

  // --- TRISTEZA (SAD) ---
  { t: "Cercano está Jehová a los quebrantados de corazón.", r: "Salmos 34:18", m: ["sad"] },
  { t: "Bienaventurados los que lloran, porque ellos recibirán consolación.", r: "Mateo 5:4", m: ["sad"] },
  { t: "Él sana a los quebrantados de corazón, y venda sus heridas.", r: "Salmos 147:3", m: ["sad"] },
  { t: "Venid a mí todos los que estáis trabajados y cargados, y yo os haré descansar.", r: "Mateo 11:28", m: ["sad"] },
  { t: "Enjugará Dios toda lágrima de los ojos de ellos; y ya no habrá muerte.", r: "Apocalipsis 21:4", m: ["sad"] },
  { t: "Por la noche durará el lloro, y a la mañana vendrá la alegría.", r: "Salmos 30:5", m: ["sad"] },
  { t: "Ciertamente llevó él nuestras enfermedades, y sufrió nuestros dolores.", r: "Isaías 53:4", m: ["sad"] },
  { t: "¿Por qué te abates, oh alma mía? Espera en Dios.", r: "Salmos 42:11", m: ["sad"] },
  { t: "Aunque ande en valle de sombra de muerte, no temeré mal alguno, porque tú estarás conmigo.", r: "Salmos 23:4", m: ["sad", "fear"] },
  { t: "Estas cosas os he hablado para que en mí tengáis paz. En el mundo tendréis aflicción; pero confiad, yo he vencido al mundo.", r: "Juan 16:33", m: ["sad"] },
  { t: "Dios es nuestro amparo y fortaleza, nuestro pronto auxilio en las tribulaciones.", r: "Salmos 46:1", m: ["sad", "fear"] },
  { t: "Mi carne y mi corazón desfallecen; mas la roca de mi corazón y mi porción es Dios para siempre.", r: "Salmos 73:26", m: ["sad"] },
  { t: "Bendito sea el Dios... padre de misericordias y Dios de toda consolación.", r: "2 Corintios 1:3", m: ["sad"] },
  { t: "Echando toda vuestra ansiedad sobre él, porque él tiene cuidado de vosotros.", r: "1 Pedro 5:7", m: ["sad", "fear"] },
  { t: "Claman los justos, y Jehová oye, y los libra de todas sus angustias.", r: "Salmos 34:17", m: ["sad"] },
  { t: "Tú cuentas mis pasos errantes; pon mis lágrimas en tu redoma.", r: "Salmos 56:8", m: ["sad"] },
  { t: "Vuelve ahora en amistad con él, y tendrás paz.", r: "Job 22:21", m: ["sad"] },
  { t: "Tengo por cierto que las aflicciones del tiempo presente no son comparables con la gloria venidera.", r: "Romanos 8:18", m: ["sad"] },
  { t: "Aunque mi padre y mi madre me dejaran, con todo, Jehová me recogerá.", r: "Salmos 27:10", m: ["sad"] },
  { t: "No temas, porque yo te redimí; te puse nombre, mío eres tú.", r: "Isaías 43:1", m: ["sad"] },

  // --- MIEDO / ANSIEDAD (FEAR) ---
  { t: "En el día que temo, yo en ti confío.", r: "Salmos 56:3", m: ["fear"] },
  { t: "No temas, porque yo estoy contigo; no desmayes, porque yo soy tu Dios.", r: "Isaías 41:10", m: ["fear"] },
  { t: "Porque no nos ha dado Dios espíritu de cobardía, sino de poder, de amor y de dominio propio.", r: "2 Timoteo 1:7", m: ["fear"] },
  { t: "Jehová es mi luz y mi salvación; ¿de quién temeré?", r: "Salmos 27:1", m: ["fear"] },
  { t: "La paz os dejo, mi paz os doy; yo no os la doy como el mundo la da. No se turbe vuestro corazón.", r: "Juan 14:27", m: ["fear"] },
  { t: "Por nada estéis afanosos, sino sean conocidas vuestras peticiones delante de Dios.", r: "Filipenses 4:6", m: ["fear"] },
  { t: "Y la paz de Dios, que sobrepasa todo entendimiento, guardará vuestros corazones.", r: "Filipenses 4:7", m: ["fear"] },
  { t: "Mira que te mando que te esfuerces y seas valiente; no temas ni desmayes.", r: "Josué 1:9", m: ["fear"] },
  { t: "El que habita al abrigo del Altísimo morará bajo la sombra del Omnipotente.", r: "Salmos 91:1", m: ["fear"] },
  { t: "Busqué a Jehová, y él me oyó, y me libró de todos mis temores.", r: "Salmos 34:4", m: ["fear"] },
  { t: "Si Dios es por nosotros, ¿quién contra nosotros?", r: "Romanos 8:31", m: ["fear"] },
  { t: "El temor del hombre pondrá lazo; mas el que confía en Jehová será levantado.", r: "Proverbios 29:25", m: ["fear"] },
  { t: "Ninguna arma forjada contra ti prosperará.", r: "Isaías 54:17", m: ["fear"] },
  { t: "No temas, manada pequeña, porque a vuestro Padre le ha placido daros el reino.", r: "Lucas 12:32", m: ["fear"] },
  { t: "Jehová está conmigo; no temeré lo que me pueda hacer el hombre.", r: "Salmos 118:6", m: ["fear"] },
  { t: "Cuando pases por las aguas, yo estaré contigo; y si por los ríos, no te anegarán.", r: "Isaías 43:2", m: ["fear"] },
  { t: "En paz me acostaré, y asimismo dormiré; porque solo tú, Jehová, me haces vivir confiado.", r: "Salmos 4:8", m: ["fear"] },
  { t: "He aquí Dios es salvación mía; me aseguraré y no temeré.", r: "Isaías 12:2", m: ["fear"] },
  { t: "Esforzaos y cobrad ánimo; no temáis, ni tengáis miedo.", r: "Deuteronomio 31:6", m: ["fear"] },
  { t: "De manera que podemos decir confiadamente: El Señor es mi ayudador; no temeré.", r: "Hebreos 13:6", m: ["fear"] },

  // --- ENOJO / IRA (ANGRY) ---
  { t: "La blanda respuesta quita la ira; mas la palabra áspera hace subir el furor.", r: "Proverbios 15:1", m: ["angry"] },
  { t: "Airaos, pero no pequéis; no se ponga el sol sobre vuestro enojo.", r: "Efesios 4:26", m: ["angry"] },
  { t: "Por esto, mis amados hermanos, todo hombre sea pronto para oír, tardo para hablar, tardo para airarse.", r: "Santiago 1:19", m: ["angry"] },
  { t: "Porque la ira del hombre no obra la justicia de Dios.", r: "Santiago 1:20", m: ["angry"] },
  { t: "El necio da rienda suelta a toda su ira, mas el sabio al fin la sosiega.", r: "Proverbios 29:11", m: ["angry"] },
  { t: "No te apresures en tu espíritu a enojarte; porque el enojo reposa en el seno de los necios.", r: "Eclesiastés 7:9", m: ["angry"] },
  { t: "El que tarda en airarse es grande de entendimiento.", r: "Proverbios 14:29", m: ["angry"] },
  { t: "Mejor es el que tarda en airarse que el fuerte; y el que se enseñorea de su espíritu, que el que toma una ciudad.", r: "Proverbios 16:32", m: ["angry"] },
  { t: "Deja la ira, y desecha el enojo; no te excites en manera alguna a hacer lo malo.", r: "Salmos 37:8", m: ["angry"] },
  { t: "La cordura del hombre detiene su furor, y su honra es pasar por alto la ofensa.", r: "Proverbios 19:11", m: ["angry"] },
  { t: "Pero yo os digo que cualquiera que se enoje contra su hermano, será culpable de juicio.", r: "Mateo 5:22", m: ["angry"] },
  { t: "No os venguéis vosotros mismos, amados míos... mía es la venganza, yo pagaré, dice el Señor.", r: "Romanos 12:19", m: ["angry"] },
  { t: "Quítense de vosotros toda amargura, enojo, ira, gritería y maledicencia.", r: "Efesios 4:31", m: ["angry"] },
  { t: "El hombre iracundo promueve contiendas; mas el que tarda en airarse apacigua la rencilla.", r: "Proverbios 15:18", m: ["angry"] },
  { t: "No paguéis a nadie mal por mal; procurad lo bueno delante de todos los hombres.", r: "Romanos 12:17", m: ["angry"] },
  { t: "Amad a vuestros enemigos, bendecid a los que os maldicen.", r: "Mateo 5:44", m: ["angry"] },
  { t: "Soportándoos unos a otros, y perdonándoos unos a otros.", r: "Colosenses 3:13", m: ["angry"] },
  { t: "No seas vencido de lo malo, sino vence con el bien el mal.", r: "Romanos 12:21", m: ["angry"] },
  { t: "El que carece de entendimiento menosprecia a su prójimo; mas el hombre prudente calla.", r: "Proverbios 11:12", m: ["angry"] },
  { t: "Antes sed benignos unos con otros, misericordiosos, perdonándoos unos a otros.", r: "Efesios 4:32", m: ["angry"] },

  // --- NEUTRAL / SABIDURÍA / FE (NEUTRAL) ---
  { t: "Es, pues, la fe la certeza de lo que se espera, la convicción de lo que no se ve.", r: "Hebreos 11:1", m: ["neutral"] },
  { t: "Fíate de Jehová de todo tu corazón, y no te apoyes en tu propia prudencia.", r: "Proverbios 3:5", m: ["neutral"] },
  { t: "Reconócelo en todos tus caminos, y él enderezará tus veredas.", r: "Proverbios 3:6", m: ["neutral"] },
  { t: "Todo lo puedo en Cristo que me fortalece.", r: "Filipenses 4:13", m: ["neutral", "happy"] },
  { t: "Lámpara es a mis pies tu palabra, y lumbrera a mi camino.", r: "Salmos 119:105", m: ["neutral"] },
  { t: "Mas buscad primeramente el reino de Dios y su justicia, y todas estas cosas os serán añadidas.", r: "Mateo 6:33", m: ["neutral"] },
  { t: "Porque yo sé los pensamientos que tengo acerca de vosotros, dice Jehová, pensamientos de paz.", r: "Jeremías 29:11", m: ["neutral", "happy"] },
  { t: "Y sabemos que a los que aman a Dios, todas las cosas les ayudan a bien.", r: "Romanos 8:28", m: ["neutral"] },
  { t: "Encomienda a Jehová tus obras, y tus pensamientos serán afirmados.", r: "Proverbios 16:3", m: ["neutral"] },
  { t: "Todas vuestras cosas sean hechas con amor.", r: "1 Corintios 16:14", m: ["neutral"] },
  { t: "Mas el fruto del Espíritu es amor, gozo, paz, paciencia, benignidad, bondad, fe...", r: "Gálatas 5:22", m: ["neutral"] },
  { t: "Porque por gracia sois salvos por medio de la fe.", r: "Efesios 2:8", m: ["neutral"] },
  { t: "Y si alguno de vosotros tiene falta de sabiduría, pídala a Dios.", r: "Santiago 1:5", m: ["neutral"] },
  { t: "Sobre toda cosa guardada, guarda tu corazón; porque de él mana la vida.", r: "Proverbios 4:23", m: ["neutral"] },
  { t: "Y todo lo que hagáis, hacedlo de corazón, como para el Señor y no para los hombres.", r: "Colosenses 3:23", m: ["neutral"] },
  { t: "Oh hombre, él te ha declarado lo que es bueno... hacer justicia, amar misericordia, y humillarte ante tu Dios.", r: "Miqueas 6:8", m: ["neutral"] },
  { t: "He aquí yo estoy con vosotros todos los días, hasta el fin del mundo.", r: "Mateo 28:20", m: ["neutral"] },
  { t: "Yo y mi casa serviremos a Jehová.", r: "Josué 24:15", m: ["neutral"] },
  { t: "Instruye al niño en su camino, y aun cuando fuere viejo no se apartará de él.", r: "Proverbios 22:6", m: ["neutral"] },
  { t: "El principio de la sabiduría es el temor de Jehová.", r: "Proverbios 1:7", m: ["neutral"] }
];
