// js/verses.js
export const versesDB = [
    // --- FORTALEZA Y PODER ---
    { r: "Salmos 23:1", t: "El Señor es mi pastor; nada me faltará." },
    { r: "Filipenses 4:13", t: "Todo lo puedo en Cristo que me fortalece." },
    { r: "Isaías 41:10", t: "No temas, porque yo estoy contigo; no desmayes, porque yo soy tu Dios que te esfuerzo." },
    { r: "Josué 1:9", t: "Mira que te mando que te esfuerces y seas valiente; no temas ni desmayes, porque el Señor tu Dios estará contigo." },
    { r: "Salmos 27:1", t: "El Señor es mi luz y mi salvación; ¿de quién temeré? El Señor es la fortaleza de mi vida." },
    { r: "Salmos 46:1", t: "Dios es nuestro amparo y fortaleza, nuestro pronto auxilio en las tribulaciones." },
    { r: "Isaías 40:31", t: "Pero los que esperan al Señor tendrán nuevas fuerzas; levantarán alas como las águilas." },
    { r: "2 Timoteo 1:7", t: "Porque no nos ha dado Dios espíritu de cobardía, sino de poder, de amor y de dominio propio." },
    { r: "Salmos 18:2", t: "El Señor, roca mía y castillo mío, y mi libertador; Dios mío, fortaleza mía, en él confiaré." },
    { r: "Salmos 28:7", t: "El Señor es mi fortaleza y mi escudo; en él confió mi corazón, y fui ayudado." },
    { r: "Éxodo 15:2", t: "El Señor es mi fortaleza y mi cántico, y ha sido mi salvación." },
    { r: "Salmos 118:14", t: "Mi fortaleza y mi cántico es el Señor, y él me ha sido por salvación." },
    { r: "Habacuc 3:19", t: "El Señor es mi fortaleza, el cual hace mis pies como de ciervas." },
    { r: "Efesios 6:10", t: "Por lo demás, hermanos míos, fortaleceos en el Señor, y en el poder de su fuerza." },
    { r: "Isaías 12:2", t: "He aquí Dios es salvación mía; me aseguraré y no temeré." },
    { r: "Nehemías 8:10", t: "No os entristezcáis, porque el gozo del Señor es vuestra fuerza." },
    { r: "Salmos 59:16", t: "Pero yo cantaré de tu poder, y alabaré de mañana tu misericordia." },
    { r: "Salmos 73:26", t: "Mi carne y mi corazón desfallecen; mas la roca de mi corazón y mi porción es Dios para siempre." },
    { r: "1 Crónicas 16:11", t: "Buscad al Señor y su poder; buscad siempre su rostro." },
    { r: "Salmos 138:3", t: "El día que clamé, me respondiste; me fortaleciste con vigor en mi alma." },
    { r: "Salmos 144:1", t: "Bendito sea el Señor, mi roca, quien adiestra mis manos para la batalla." },
    { r: "Proverbios 18:10", t: "Torre fuerte es el nombre del Señor; a él correrá el justo, y será levantado." },

    // --- PAZ Y CONSUELO ---
    { r: "Filipenses 4:6-7", t: "Por nada estéis afanosos... y la paz de Dios guardará vuestros corazones." },
    { r: "Juan 14:27", t: "La paz os dejo, mi paz os doy; yo no os la doy como el mundo la da." },
    { r: "Salmos 4:8", t: "En paz me acostaré, y asimismo dormiré; porque solo tú, Señor, me haces vivir confiado." },
    { r: "Mateo 11:28", t: "Venid a mí todos los que estáis trabajados y cargados, y yo os haré descansar." },
    { r: "1 Pedro 5:7", t: "Echando toda vuestra ansiedad sobre él, porque él tiene cuidado de vosotros." },
    { r: "Salmos 34:4", t: "Busqué al Señor, y él me oyó, y me libró de todos mis temores." },
    { r: "Isaías 26:3", t: "Tú guardarás en completa paz a aquel cuyo pensamiento en ti persevera." },
    { r: "Salmos 55:22", t: "Echa sobre el Señor tu carga, y él te sustentará." },
    { r: "2 Tesalonicenses 3:16", t: "Y el mismo Señor de paz os dé siempre paz en toda manera." },
    { r: "Colosenses 3:15", t: "Y la paz de Dios gobierne en vuestros corazones." },
    { r: "Salmos 119:165", t: "Mucha paz tienen los que aman tu ley, y no hay para ellos tropiezo." },
    { r: "Proverbios 3:24", t: "Cuando te acuestes, no tendrás temor, sino que tu sueño será grato." },
    { r: "Salmos 94:19", t: "En la multitud de mis pensamientos, tus consolaciones alegraban mi alma." },
    { r: "Juan 16:33", t: "En el mundo tendréis aflicción; pero confiad, yo he vencido al mundo." },
    { r: "Salmos 29:11", t: "El Señor dará poder a su pueblo; el Señor bendecirá a su pueblo con paz." },
    { r: "Isaías 32:17", t: "Y el efecto de la justicia será paz; y la labor de la justicia, reposo y seguridad." },
    { r: "Mateo 5:9", t: "Bienaventurados los pacificadores, porque ellos serán llamados hijos de Dios." },
    { r: "Romanos 15:13", t: "Y el Dios de esperanza os llene de todo gozo y paz en el creer." },

    // --- AMOR Y MISERICORDIA ---
    { r: "Juan 3:16", t: "Porque de tal manera amó Dios al mundo, que ha dado a su Hijo unigénito." },
    { r: "Romanos 5:8", t: "Mas Dios muestra su amor para con nosotros, en que siendo aún pecadores, Cristo murió por nosotros." },
    { r: "1 Juan 4:19", t: "Nosotros le amamos a él, porque él nos amó primero." },
    { r: "Jeremías 31:3", t: "Con amor eterno te he amado; por tanto, te prolongué mi misericordia." },
    { r: "Romanos 8:38-39", t: "Nada nos podrá separar del amor de Dios, que es en Cristo Jesús." },
    { r: "Efesios 2:8", t: "Porque por gracia sois salvos por medio de la fe; y esto no de vosotros, pues es don de Dios." },
    { r: "Lamentaciones 3:22-23", t: "Por la misericordia del Señor no hemos sido consumidos; nuevas son cada mañana." },
    { r: "Salmos 86:15", t: "Mas tú, Señor, Dios misericordioso y clemente, lento para la ira, y grande en misericordia." },
    { r: "Sofonías 3:17", t: "El Señor está en medio de ti... callará de amor, se regocijará sobre ti con cánticos." },
    { r: "1 Juan 3:1", t: "Mirad cuál amor nos ha dado el Padre, para que seamos llamados hijos de Dios." },
    { r: "Gálatas 2:20", t: "El cual me amó y se entregó a sí mismo por mí." },
    { r: "Salmos 136:1", t: "Alabad al Señor, porque él es bueno, porque para siempre es su misericordia." },
    { r: "Salmos 103:8", t: "Misericordioso y clemente es el Señor; lento para la ira, y grande en misericordia." },
    { r: "Proverbios 8:17", t: "Yo amo a los que me aman, y me hallan los que temprano me buscan." },
    { r: "1 Juan 4:8", t: "El que no ama, no ha conocido a Dios; porque Dios es amor." },
    { r: "1 Juan 4:16", t: "Y nosotros hemos conocido y creído el amor que Dios tiene para con nosotros." },
    { r: "Romanos 8:31", t: "¿Qué, pues, diremos a esto? Si Dios es por nosotros, ¿quién contra nosotros?" },
    { r: "Salmos 36:7", t: "¡Cuán preciosa, oh Dios, es tu misericordia! Por eso los hijos de los hombres se amparan bajo la sombra de tus alas." },

    // --- SABIDURÍA Y GUÍA ---
    { r: "Proverbios 3:5-6", t: "Fíate del Señor de todo tu corazón... Reconócelo en todos tus caminos." },
    { r: "Salmos 119:105", t: "Lámpara es a mis pies tu palabra, y lumbrera a mi camino." },
    { r: "Santiago 1:5", t: "Y si alguno de vosotros tiene falta de sabiduría, pídala a Dios." },
    { r: "Salmos 32:8", t: "Te haré entender, y te enseñaré el camino en que debes andar." },
    { r: "Jeremías 33:3", t: "Clama a mí, y yo te responderé, y te enseñaré cosas grandes y ocultas." },
    { r: "Proverbios 16:3", t: "Encomienda al Señor tus obras, y tus pensamientos serán afirmados." },
    { r: "Salmos 37:5", t: "Encomienda al Señor tu camino, y confía en él; y él hará." },
    { r: "Proverbios 1:7", t: "El principio de la sabiduría es el temor del Señor." },
    { r: "Salmos 143:10", t: "Enséñame a hacer tu voluntad, porque tú eres mi Dios." },
    { r: "Isaías 30:21", t: "Entonces tus oídos oirán a tus espaldas palabra que diga: Este es el camino, andad por él." },
    { r: "Salmos 25:4", t: "Muéstrame, oh Señor, tus caminos; enséñame tus sendas." },
    { r: "Proverbios 2:6", t: "Porque el Señor da la sabiduría, y de su boca viene el conocimiento." },
    { r: "Romanos 12:2", t: "Transformaos por medio de la renovación de vuestro entendimiento." },
    { r: "Salmos 73:24", t: "Me has guiado según tu consejo, y después me recibirás en gloria." },
    { r: "Proverbios 9:10", t: "El temor del Señor es el principio de la sabiduría." },
    { r: "Santiago 3:17", t: "Pero la sabiduría que es de lo alto es primeramente pura, después pacífica, amable." },
    { r: "Salmos 25:9", t: "Encaminará a los humildes por el juicio, y enseñará a los mansos su carrera." },
    { r: "Proverbios 16:9", t: "El corazón del hombre piensa su camino; mas el Señor endereza sus pasos." },

    // --- PROTECCIÓN ---
    { r: "Salmos 91:1-2", t: "El que habita al abrigo del Altísimo morará bajo la sombra del Omnipotente." },
    { r: "Salmos 91:11", t: "Pues a sus ángeles mandará acerca de ti, que te guarden en todos tus caminos." },
    { r: "Salmos 121:7", t: "El Señor te guardará de todo mal; él guardará tu alma." },
    { r: "Isaías 54:17", t: "Ninguna arma forjada contra ti prosperará." },
    { r: "Salmos 34:7", t: "El ángel del Señor acampa alrededor de los que le temen, y los defiende." },
    { r: "Salmos 121:1-2", t: "Mi socorro viene del Señor, que hizo los cielos y la tierra." },
    { r: "2 Tesalonicenses 3:3", t: "Pero fiel es el Señor, que os afirmará y guardará del mal." },
    { r: "Salmos 3:3", t: "Mas tú, Señor, eres escudo alrededor de mí; mi gloria, y el que levanta mi cabeza." },
    { r: "Salmos 138:7", t: "Si anduviere yo en medio de la angustia, tú me vivificarás." },
    { r: "Deuteronomio 31:6", t: "El Señor tu Dios es el que va contigo; no te dejará ni te desamparará." },
    { r: "Salmos 16:1", t: "Guárdame, oh Dios, porque en ti he confiado." },
    { r: "Salmos 121:8", t: "El Señor guardará tu salida y tu entrada desde ahora y para siempre." },
    { r: "Proverbios 30:5", t: "Toda palabra de Dios es limpia; él es escudo a los que en él esperan." },
    { r: "Salmos 23:4", t: "Aunque ande en valle de sombra de muerte, no temeré mal alguno, porque tú estarás conmigo." },
    { r: "Salmos 5:11", t: "Pero alégrense todos los que en ti confían; den voces de júbilo para siempre, porque tú los defiendes." },
    { r: "Isaías 43:2", t: "Cuando pases por las aguas, yo estaré contigo; y si por los ríos, no te anegarán." },

    // --- FE Y ESPERANZA ---
    { r: "Jeremías 29:11", t: "Porque yo sé los pensamientos que tengo acerca de vosotros, dice el Señor, pensamientos de paz." },
    { r: "Romanos 8:28", t: "Y sabemos que a los que aman a Dios, todas las cosas les ayudan a bien." },
    { r: "Hebreos 11:1", t: "Es, pues, la fe la certeza de lo que se espera, la convicción de lo que no se ve." },
    { r: "2 Corintios 5:7", t: "Porque por fe andamos, no por vista." },
    { r: "Marcos 9:23", t: "Jesús le dijo: Si puedes creer, al que cree todo le es posible." },
    { r: "Lucas 1:37", t: "Porque nada hay imposible para Dios." },
    { r: "Salmos 37:4", t: "Deléitate asimismo en el Señor, y él te concederá las peticiones de tu corazón." },
    { r: "Mateo 17:20", t: "Si tuviereis fe como un grano de mostaza... nada os será imposible." },
    { r: "Salmos 62:5", t: "Alma mía, en Dios solamente reposa, porque de él es mi esperanza." },
    { r: "Salmos 71:5", t: "Porque tú, oh Señor Dios, eres mi esperanza, seguridad mía desde mi juventud." },
    { r: "Lamentaciones 3:24", t: "Mi porción es el Señor, dijo mi alma; por tanto, en él esperaré." },
    { r: "Isaías 43:19", t: "He aquí que yo hago cosa nueva; pronto saldrá a luz." },
    { r: "Hebreos 10:23", t: "Mantengamos firme, sin fluctuar, la profesión de nuestra esperanza, porque fiel es el que prometió." },
    { r: "Salmos 42:11", t: "¿Por qué te abates, oh alma mía? Espera en Dios; porque aún he de alabarle." },
    { r: "Romanos 10:17", t: "Así que la fe es por el oír, y el oír, por la palabra de Dios." },
    { r: "1 Pedro 1:21", t: "Y mediante el cual creéis en Dios... para que vuestra fe y esperanza sean en Dios." },
    { r: "Salmos 39:7", t: "Y ahora, Señor, ¿qué esperaré? Mi esperanza está en ti." },

    // --- ALABANZA Y GRATITUD ---
    { r: "Salmos 150:6", t: "Todo lo que respira alabe al Señor. Aleluya." },
    { r: "Salmos 103:1", t: "Bendice, alma mía, al Señor, y bendiga todo mi ser su santo nombre." },
    { r: "1 Tesalonicenses 5:18", t: "Dad gracias en todo, porque esta es la voluntad de Dios." },
    { r: "Salmos 118:24", t: "Este es el día que hizo el Señor; nos gozaremos y alegraremos en él." },
    { r: "Salmos 19:1", t: "Los cielos cuentan la gloria de Dios, y el firmamento anuncia la obra de sus manos." },
    { r: "Salmos 100:4", t: "Entrad por sus puertas con acción de gracias, por sus atrios con alabanza." },
    { r: "Salmos 34:1", t: "Bendeciré al Señor en todo tiempo; su alabanza estará de continuo en mi boca." },
    { r: "Salmos 95:1", t: "Venid, aclamemos alegremente al Señor; cantemos con júbilo a la roca de nuestra salvación." },
    { r: "Salmos 107:1", t: "Alabad al Señor, porque él es bueno; porque para siempre es su misericordia." },
    { r: "Colosenses 3:17", t: "Y todo lo que hacéis... hacedlo todo en el nombre del Señor Jesús, dando gracias." },
    { r: "Salmos 92:1", t: "Bueno es alabarte, oh Señor, y cantar salmos a tu nombre." },
    { r: "Efesios 5:20", t: "Dando siempre gracias por todo al Dios y Padre." },
    { r: "Salmos 8:1", t: "¡Oh Señor, Señor nuestro, cuán glorioso es tu nombre en toda la tierra!" },
    { r: "Salmos 63:3", t: "Porque mejor es tu misericordia que la vida; mis labios te alabarán." },
    { r: "Salmos 100:1", t: "Cantad alegres a Dios, habitantes de toda la tierra." },
    { r: "Salmos 145:1", t: "Te exaltaré, mi Dios, mi Rey, y bendeciré tu nombre eternamente y para siempre." },
    { r: "Apocalipsis 4:11", t: "Señor, digno eres de recibir la gloria y la honra y el poder." },

    // --- VIDA Y CAMINAR DIARIO ---
    { r: "Mateo 5:14", t: "Vosotros sois la luz del mundo." },
    { r: "Gálatas 5:22-23", t: "Mas el fruto del Espíritu es amor, gozo, paz, paciencia, benignidad, bondad, fe..." },
    { r: "Miqueas 6:8", t: "Oh hombre, él te ha declarado lo que es bueno... hacer justicia, y amar misericordia." },
    { r: "Josué 24:15", t: "Pero yo y mi casa serviremos al Señor." },
    { r: "Romanos 12:21", t: "No seas vencido de lo malo, sino vence con el bien el mal." },
    { r: "Colosenses 3:23", t: "Y todo lo que hagáis, hacedlo de corazón, como para el Señor." },
    { r: "Mateo 6:33", t: "Mas buscad primeramente el reino de Dios y su justicia." },
    { r: "1 Corintios 16:14", t: "Todas vuestras cosas sean hechas con amor." },
    { r: "Efesios 4:32", t: "Antes sed benignos unos con otros, misericordiosos, perdonándoos unos a otros." },
    { r: "Santiago 1:22", t: "Pero sed hacedores de la palabra, y no tan solamente oidores." },
    { r: "Salmos 1:1", t: "Bienaventurado el varón que no anduvo en consejo de malos." },
    { r: "Salmos 119:11", t: "En mi corazón he guardado tus dichos, para no pecar contra ti." },
    { r: "Proverbios 22:6", t: "Instruye al niño en su camino, y aun cuando fuere viejo no se apartará de él." },
    { r: "Mateo 22:37", t: "Amarás al Señor tu Dios con todo tu corazón, y con toda tu alma." },
    { r: "Salmos 133:1", t: "¡Mirad cuán bueno y cuán delicioso es habitar los hermanos juntos en armonía!" },
    { r: "Efesios 5:16", t: "Aprovechando bien el tiempo, porque los días son malos." },
    { r: "1 Corintios 10:31", t: "Si, pues, coméis o bebéis, o hacéis otra cosa, hacedlo todo para la gloria de Dios." },
    { r: "Santiago 4:8", t: "Acercaos a Dios, y él se acercará a vosotros." },
    { r: "1 Pedro 2:9", t: "Mas vosotros sois linaje escogido, real sacerdocio, nación santa, pueblo adquirido por Dios." },

    // --- SALVACIÓN Y CRISTO ---
    { r: "Juan 14:6", t: "Jesús le dijo: Yo soy el camino, y la verdad, y la vida." },
    { r: "Hechos 4:12", t: "Y en ningún otro hay salvación." },
    { r: "Romanos 10:9", t: "Que si confesares con tu boca que Jesús es el Señor... serás salvo." },
    { r: "2 Corintios 5:17", t: "De modo que si alguno está en Cristo, nueva criatura es." },
    { r: "1 Juan 1:9", t: "Si confesamos nuestros pecados, él es fiel y justo para perdonar." },
    { r: "Apocalipsis 3:20", t: "He aquí, yo estoy a la puerta y llamo." },
    { r: "Juan 1:1", t: "En el principio era el Verbo, y el Verbo era con Dios." },
    { r: "Juan 8:32", t: "Y conoceréis la verdad, y la verdad os hará libres." },
    { r: "Juan 10:10", t: "Yo he venido para que tengan vida, y para que la tengan en abundancia." },
    { r: "Mateo 28:20", t: "Y he aquí yo estoy con vosotros todos los días, hasta el fin del mundo." },
    { r: "Romanos 6:23", t: "Porque la paga del pecado es muerte, mas la dádiva de Dios es vida eterna." },
    { r: "1 Timoteo 2:5", t: "Porque hay un solo Dios, y un solo mediador entre Dios y los hombres, Jesucristo hombre." },
    { r: "Hebreos 4:12", t: "Porque la palabra de Dios es viva y eficaz." },
    { r: "1 Juan 5:14", t: "Y esta es la confianza que tenemos en él, que si pedimos alguna cosa conforme a su voluntad, él nos oye." },
    { r: "Isaías 53:5", t: "Mas él herido fue por nuestras rebeliones, molido por nuestros pecados." },
    { r: "Juan 6:35", t: "Jesús les dijo: Yo soy el pan de vida; el que a mí viene, nunca tendrá hambre." },
    { r: "Hechos 16:31", t: "Cree en el Señor Jesucristo, y serás salvo, tú y tu casa." },
    { r: "Efesios 1:7", t: "En quien tenemos redención por su sangre, el perdón de pecados." },
    { r: "Colosenses 1:13-14", t: "El cual nos ha librado de la potestad de las tinieblas, y trasladado al reino de su amado Hijo." },
    { r: "Tito 3:5", t: "Nos salvó, no por obras de justicia que nosotros hubiéramos hecho, sino por su misericordia." },

    // --- PROMESAS Y BENDICIÓN ---
    { r: "Números 6:24", t: "El Señor te bendiga, y te guarde." },
    { r: "Deuteronomio 28:13", t: "Te pondrá el Señor por cabeza, y no por cola." },
    { r: "Salmos 37:25", t: "Joven fui, y he envejecido, y no he visto justo desamparado, ni su descendencia que mendigue pan." },
    { r: "Malaquías 3:10", t: "Probadme ahora en esto, dice el Señor... si no os abriré las ventanas de los cielos." },
    { r: "2 Corintios 9:8", t: "Y poderoso es Dios para hacer que abunde en vosotros toda gracia." },
    { r: "Filipenses 4:19", t: "Mi Dios, pues, suplirá todo lo que os falta conforme a sus riquezas en gloria." },
    { r: "Salmos 84:11", t: "Porque sol y escudo es el Señor Dios; gracia y gloria dará el Señor." },
    { r: "Isaías 49:15", t: "¿Se olvidará la mujer de lo que dio a luz?... Aunque olvide ella, yo nunca me olvidaré de ti." },
    { r: "Jeremías 32:27", t: "He aquí que yo soy el Señor, Dios de toda carne; ¿habrá algo que sea difícil para mí?" },
    { r: "Lamentaciones 3:25", t: "Bueno es el Señor a los que en él esperan, al alma que le busca." },
    { r: "Salmos 68:19", t: "Bendito el Señor; cada día nos colma de beneficios el Dios de nuestra salvación." },
    { r: "Santiago 1:17", t: "Toda buena dádiva y todo don perfecto desciende de lo alto." },
    { r: "1 Juan 2:25", t: "Y esta es la promesa que él nos hizo, la vida eterna." },
    { r: "Apocalipsis 21:4", t: "Enjugará Dios toda lágrima de los ojos de ellos; y ya no habrá muerte." },
    { r: "Salmos 126:5", t: "Los que sembraron con lágrimas, con regocijo segarán." },
    { r: "Salmos 1:3", t: "Será como árbol plantado junto a corrientes de aguas, que da su fruto en su tiempo." },
    { r: "Isaías 55:11", t: "Así será mi palabra que sale de mi boca; no volverá a mí vacía." },
    { r: "Salmos 147:3", t: "Él sana a los quebrantados de corazón, y venda sus heridas." },
    { r: "Proverbios 10:22", t: "La bendición del Señor es la que enriquece, y no añade tristeza con ella." },
    { r: "Salmos 34:10", t: "Los leoncillos necesitan, y tienen hambre; pero los que buscan al Señor no tendrán falta de ningún bien." },
    { r: "Salmos 37:37", t: "Considera al íntegro, y mira al justo; porque hay un final dichoso para el hombre de paz." },
    { r: "Proverbios 4:18", t: "Mas la senda de los justos es como la luz de la aurora, que va en aumento hasta que el día es perfecto." },
    { r: "Isaías 58:11", t: "El Señor te pastoreará siempre, y en las sequías saciará tu alma." },
    { r: "Jeremías 17:7", t: "Bendito el varón que confía en el Señor, y cuya confianza es el Señor." },
    { r: "Mateo 7:7", t: "Pedid, y se os dará; buscad, y hallaréis; llamad, y se os abrirá." },
    { r: "Juan 15:7", t: "Si permanecéis en mí, y mis palabras permanecen en vosotros, pedid todo lo que queréis, y os será hecho." },
    { r: "Romanos 4:21", t: "Plenamente convencido de que era también poderoso para hacer todo lo que había prometido." },
    { r: "2 Pedro 3:9", t: "El Señor no retarda su promesa, según algunos la tienen por tardanza, sino que es paciente." },
    { r: "Salmos 128:1", t: "Bienaventurado todo aquel que teme al Señor, que anda en sus caminos." }
];
